name: Update README
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Update this repo's README with recent activity
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Add activity to readme
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}